Repository GSM-MSG/Salt-Bot, pull requests merged in 2024-03, with the labels that each got.

#17 🔀 :: Job Service 환경 추가
  package.json
  src/MSGSaltBot.ts
  src/index.ts
  src/interfaces/Job.ts
  src/services/JobService.ts
Labels: ⚙ Setting

#18 🔀 :: Schedule 도메인 관련 데이터 작업 객체 추가
  src/models/Schedule.ts
  src/repositories/ScheduleRepository.ts
Labels: ⚙ Setting

#19 🔀 :: 일정 추가 Command 추가
  package.json
  src/commands/AddScheduleCommand.ts
  src/utils/FormatUtils.ts
Labels: ✨ Feature

#20 🔀 :: 등록된 일정 리스트 Command
  src/commands/FetchScheduleListCommand.ts
Labels: ✨ Feature

#21 🔀 :: 일정 삭제 Command 추가
  src/commands/DeleteScheduleCommand.ts
Labels: ✨ Feature

#22 🔀 :: 일정 동기화 Command 추가
  src/commands/SyncScheduleCommand.ts
Labels: ✨ Feature

#23 🔀 : :: 일정 리마인더 Job 추가
  src/jobs/ReminderSchedulerJob.ts
Labels: ✨ Feature

#24 🔀 : :: 일정 알림 Job 추가
  package.json
  src/jobs/SchedulerJob.ts
Labels: ✨ Feature

#25 🔀 :: 오늘 잡혀있는 일정을 보내주는 Job 추가
  src/jobs/TodayScheduleJob.ts
Labels: ✨ Feature

#26 🔀 :: Schedule 도메인 관련 Command와 Job 봇에 등록
  src/MSGSaltBot.ts
  src/index.ts
Labels: ⚙ Setting, ⚡️ Simple

#29 🔀 :: 오늘 일정 알림 Job 등록
  src/index.ts
Labels: 🐞 Bug

#32 🔀 :: [#30] 스케쥴 동기화 실행 시, 하나의 일정만 설정됨
  src/repositories/ScheduleRepository.ts
Labels: 🐞 Bug

#37 ♻️ 회의에 늦은 팀원 부르기 유효기간 15분으로 늘리기
  src/jobs/SchedulerJob.ts
Labels: 1️⃣ Priority: High, ♻️ Refactor

#38 🔀 :: 일정 생성 입력 유효기간 1분 -> 5분
  src/commands/AddScheduleCommand.ts
Labels: 1️⃣ Priority: High, ♻️ Refactor
